version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-backend
    restart: always
    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend-app
    depends_on:
      - postgres
    ports:
      - "8097:8097"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backenddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata: